project:
  type: website
  output-dir: docs

website:
  title: "Climate and forest regeneration"
  navbar:
    left:
      - href: index.qmd
        text: "<i class='bi bi-book-half'></i> About"
      - href: code_climate_forest_regeneration.qmd
        text: "<i class='bi bi-bar-chart-fill'></i> Data Analysis"
    right:
      - href: https://github.com/LaisRosaOliveira/paper_climate_forest_regeneration
        text: "<i class='bi bi-github'></i> GitHub"
      - href: https://www.linkedin.com/in/lais-rosa-a68975253/
        text: "<i class='bi bi-linkedin'></i> Linkedin"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


